// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC079P1ZUJi9XUflCnuFb-AdElSsrKKMI',
    appId: '1:1096650635952:web:c220bcc96ef8115f67d975',
    messagingSenderId: '1096650635952',
    projectId: 'bookly-application-f15b2',
    authDomain: 'bookly-application-f15b2.firebaseapp.com',
    storageBucket: 'bookly-application-f15b2.firebasestorage.app',
    measurementId: 'G-N0E3XCVBX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMMJ4mbWMyOM9jPVbJs7p1G5LO0cyVaU',
    appId: '1:1096650635952:android:b589ae66386dd43b67d975',
    messagingSenderId: '1096650635952',
    projectId: 'bookly-application-f15b2',
    storageBucket: 'bookly-application-f15b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyjYw2gm-8-EvUQMk-vSb1STNGLFWKXZE',
    appId: '1:1096650635952:ios:af589f87df35589267d975',
    messagingSenderId: '1096650635952',
    projectId: 'bookly-application-f15b2',
    storageBucket: 'bookly-application-f15b2.firebasestorage.app',
    iosBundleId: 'com.example.booklyApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyjYw2gm-8-EvUQMk-vSb1STNGLFWKXZE',
    appId: '1:1096650635952:ios:af589f87df35589267d975',
    messagingSenderId: '1096650635952',
    projectId: 'bookly-application-f15b2',
    storageBucket: 'bookly-application-f15b2.firebasestorage.app',
    iosBundleId: 'com.example.booklyApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC079P1ZUJi9XUflCnuFb-AdElSsrKKMI',
    appId: '1:1096650635952:web:5d257f1954a35faa67d975',
    messagingSenderId: '1096650635952',
    projectId: 'bookly-application-f15b2',
    authDomain: 'bookly-application-f15b2.firebaseapp.com',
    storageBucket: 'bookly-application-f15b2.firebasestorage.app',
    measurementId: 'G-BJKXNFZGWX',
  );
}
